### ISSUE TITLE
Tuning and fixes for new welcome page

### ISSUE THREAD

**Issue by sigdestad** [enonic/app-xp-welcome#127]
General: Replace "Envionment" with "Sandbox" 

Boot page:
- [x] Title seems to be using bold? Change to bigger font without bold?
- [ ] Clicking browser back button seems to always take me to enonic admin login?

Cards:
- [x] "Extensible and customizable administrative user interface" -> "Sandbox admin web interface"
- [x] Content card subtitle: "8080:/site" -> "Content projects"
- [x] Site card subtitle: "all sites" -> ":8080/site"
- [x] Webapp card "Build and host web app using Enonic JS framework" -> "Build and host webapps without 3rd party tools"
- [ ] Metrics, use button "Browse metrics API", no external link
- [x] "Hide secondary endpoints" -> "Collapse endpoints"

Apps
- [x] App list should not use bold font.
- [x] There is no link to admin app for Explorer 2.0 - for some reason?

Sub pages: 
- [x] Title always says "Welcome to.." - but should say "Webapps", "Sites", "Content projects" etc
- [x] On subpages, change from "localhost:8080" -> "< Back" with a link (maybe make the text a bit bigger also?)

Projects list:
- [x] Project subtitle: Use only project name, not /site/project-name
- [ ] Use button for "Open in content studio", no external link icon

Webapp list:
- [x] Project subtitle: Use only webapp name, not /webapp/app-name
- [ ] Use button for "Open webapp", no external link icon

Sites list:
- [x] Project subtitle: drop <branch> element in path
- [ ] Use button for "Open in Content Studio", no external link

**Comment by edloidas** [comment]
Not sure what you mean by "Clicking browser back button seems to always take me to enonic admin login". Welcome app is a SPA. Clicking Back button in the browser will take you to previous browser page (e.g. it may be an empty new tab).

**Comment by edloidas** [comment]
Explorer 2.0 has both admin/tools and webapps folders. We only show links to the apps, that have a single endpoint assigned to them.

**Comment by edloidas** [comment]
> change from "localhost:8080" -> "< Back" with a link (maybe make the text a bit bigger also?)
I assume you want to gt rid of the navigation path completelly? There won't be any nesting, like `localhost:8080 / sites / branch / ...` ?

**Comment by edloidas** [comment]
> Use button for "Open webapp", no external link icon
If you want to have a big blue button everywhere, it may be confusing for users. ATM, buttons do what they meant to: running some actions and changing the app state, e.g. browsing the specific categories. But "Open in CS" is actually a link, that opens a new browser tab.

**Comment by sigdestad** [comment]
I simply want as much consistency as possible. The login for instance is also a button. In general we should reduce new tabs to external links only. So, for instance, when opening in Content Studio this is still on localhost, and should not open in new tab.

You can also add these new tasks to the list then:

* Avoid new tabs with exception of docs (external links)
* Don't store navigation state (its confusing that it stores the state of this simple app)
* Show deeplink url when navigating

**Comment by sigdestad** [comment]
> Explorer 2.0 has both admin/tools and webapps folders. We only show links to the apps, that have a single endpoint assigned to them.

Ah.. Maybe that is too strict? 
We only link to admin tools from here, so how about changing the check to "show link if app contains a single admin tool" ?

**Comment by edloidas** [comment]
What do you mean by "_Show deeplink url when navigating_"? Showing it where? Like changing the URL in the browser, according to what view in Welcome App we are looking at?

**Comment by edloidas** [comment]
As for the buttons, the Log In is really a special case. Meanwhile, Log In as Guest will log you in from the current page without redirections.
What if we remove the external link icon if it's not linking to different origin (outside localhost), but keep the current style (uppercase, without background) for links? Using buttons with blue background everywhere is not about consistency, as these elements behave differently, also it creates more visual noise.

**Comment by sigdestad** [comment]
> What do you mean by "_Show deeplink url when navigating_"? Showing it where? Like changing the URL in the browser, according to what view in Welcome App we are looking at?

Yes

**Comment by sigdestad** [comment]
> As for the buttons, the Log In is really a special case. Meanwhile, Log In as Guest will log you in from the current page without redirections. What if we remove the external link icon if it's not linking to different origin (outside localhost), but keep the current style (uppercase, without background) for links? Using buttons with blue background everywhere is not about consistency, as these elements behave differently, also it creates more visual noise.

Let's try this first then...

**Comment by sigdestad** [comment]
> > change from "localhost:8080" -> "< Back" with a link (maybe make the text a bit bigger also?)
> > I assume you want to gt rid of the navigation path completelly? There won't be any nesting, like `localhost:8080 / sites / branch / ...` ?

Yes

**Comment by sigdestad** [comment]
> Not sure what you mean by "Clicking browser back button seems to always take me to enonic admin login". Welcome app is a SPA. Clicking Back button in the browser will take you to previous browser page (e.g. it may be an empty new tab).

But it does not work. Try visiting a sub page and click browser back
