### ISSUE TITLE
Correct some shortcomings is ci/cd process

### ISSUE THREAD

**Issue by rymsha** [enonic/app-xp-welcome#31]
- [x]  Issue Labels are not in sync with XP distro labels.
- [x] newer SNAPSHOT version of XP does not trigger build of Welcome App
- [x] new SNAPSHOT version of welcome-app does not trigger new distro SNAPSHOT
- [x] XP distro changelog does not list changes in Welcome App

**Comment by jsi** [comment]
@rymsha : What are the labels like "dependencies" and "java" used for?  Do they have to be lower case?  All our internal labels use uppercase for the first letter.  (This is not required by any ISO procedure, but it looks a lot better. 😜 )

**Comment by rymsha** [comment]
these are dependabot labels. we didn't make them. yes they have to be lowercase.

BTW, It is a deviation from common practice that we use Capital case labels.

**Comment by jsi** [comment]
Task #3 and #4 seem to be done.  At least xp-distro is triggered by app-xp-welcome, and the code is there to include the changelog, although I have not found any examples of it happening, as there were no applicable changes in app-xp-welcome in neither 7.8.0, 7.9.0 nor 7.10.0.
