### ISSUE TITLE
Projects Panel - Default project should not be displayed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/app-xp-welcome#367]
1. Create  new sandbox with  ` Next.XP demo` for example
2. Start the sandbox then navigate to the welcome page, click on `Browse projects` button

**BUG** - Deafult project should be hidden in the  `Projects Panel `

![image](https://github.com/enonic/app-xp-welcome/assets/3728712/7e98a4b7-769d-4e26-bea2-7cba20236972)

**Comment by rymsha** [comment]
In XP8 default project is not created on XP startup. And it would not be a good idea to hide a project named "default" as it might be a user who creates a project named "default"
