### ISSUE TITLE
UI polishing

### ISSUE THREAD

**Issue by alansemenov** [enonic/app-xp-welcome#83]
* Seems like state of the "Show secondary endpoints" toggler is stored somewhere. This is not needed, the list should always be collapsed by default
* Rename "Vhost" -> "Vhosts" and make it third in the list (after Content)
* "Webapp" -> "Webapps"
* Remove "v" from app version number
* system apps (like Users) should not be in the list
* apps with no links should not have hover effect

**Comment by edloidas** [comment]
I guess this can be considered a done?
